# Generated by Django 4.1.5 on 2023-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_reg", models.TextField(unique=True)),
                ("stu_name", models.TextField()),
                ("stu_email", models.EmailField(max_length=254)),
                ("stu_mo", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
